#!/bin/bash
#
#	/etc/init.d/laberp-equipment-server
#
# Starts the laberp-equipment-server daemon
#
# chkconfig: 345 95 5
# description: Run the PHP Socket Server for communicating with scales
# processname: laberp-equipment-server
 
# Source function library.
. /etc/init.d/functions
 
#startup values
log=/var/log/laberp-equipment-server.log
 
#verify that the executable exists
test -x /usr/local/laberp-equipment-server/bin/laberp-equipment-server || exit 0 RETVAL=0 
 
#
#	Set prog, proc and bin variables.
#
prog="laberp_equipment_server"
proc=/var/lock/subsys/laberp_equipment_server_php
bin=/usr/local/laberp-equipment-server/bin/laberp-equipment-server
 
start() {
	# Check if Daemon is already running
	if [ ! -f $proc ]; then
	    echo -n $"Starting $prog: "
	    daemon $bin --log=$log
	    RETVAL=$?
	    [ $RETVAL -eq 0 ] && touch $proc
	    echo
	fi
 
	return $RETVAL
}
 
stop() {
	echo -n $"Stopping $prog: "
	killproc $bin
	RETVAL=$?
	[ $RETVAL -eq 0 ] && rm -f $proc
	echo
        return $RETVAL
}
 
restart() {
	stop
	start
}	
 
reload() {
	restart
}	
 
status_at() {
 	status $bin
}
 
case "$1" in
start)
	start
	;;
stop)
	stop
	;;
reload|restart)
	restart
	;;
condrestart)
        if [ -f $proc ]; then
            restart
        fi
        ;;
status)
	status_at
	;;
*)
 
echo $"Usage: $0 {start|stop|restart|condrestart|status}"
	exit 1
esac
 
exit $?
exit $RETVAL
